name = "FormalisingMathematics2026"
defaultTargets = ["FormalisingMathematics2026"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.longLine = true

[[require]]
name = "mathlib"
rev = "v4.26.0"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "FormalisingMathematics2026"
